---
- name: OpenVPN | package | Ensure the APT cache is up to date
  apt:
    update_cache: yes
  changed_when: False
  when: ansible_os_family == "Debian"

- name: OpenVPN | package | Install openvpn
  apt:
    pkg:
      - openvpn 

- name: OpenVPN | package | Install pexpect via pip
  pip:
    name: "pexpect"
