- name: Add clients to OpenVPN's PKI
# ========================================================
  # Allows caller to override hosts using '-e cmd_hosts='
  hosts: openvpn
  become: yes
  gather_facts: yes

  roles:
    - add_clients
